### ISSUE TITLE
Rollup Production build Chart Not Exported

### ISSUE THREAD

**Issue by rodhoward** [highcharts/highcharts-vue#75]
Using the specific import option:
```
import { Chart } from "highcharts-vue";
```

Works really well using Webpack in dev environment. However when building our widget for production we are using Rollup and I'm getting this error:

```
Error: 'Chart' is not exported by node_modules/highcharts-vue/dist/module/highcharts-vue.min.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/lib-components/alchemy-chart.vue?rollup-plugin-vue=script.js (8:9)
 6: //
 7: 
 8: import { Chart } from "highcharts-vue";
             ^
 9: 
10: export default {

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rod/.npm/_logs/2019-04-26T00_31_27_126Z-debug.log
Error: 'Chart' is not exported by node_modules/highcharts-vue/dist/module/highcharts-vue.min.js
    at error (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:13349:9)
    at handleMissingExport (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:13039:21)
    at Module.traceVariable (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:13453:17)
    at ModuleScope.findVariable (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:12726:29)
    at Identifier$$1.bind (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:10111:40)
    at Identifier$$1.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:10178:18)
    at Property.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:11980:24)
    at ObjectExpression$$1.deoptimizeAllProperties (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:11754:22)
    at ObjectExpression$$1.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:11725:22)
    at Property.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:11980:24)
    at ObjectExpression$$1.deoptimizeAllProperties (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:11754:22)
    at ObjectExpression$$1.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:11725:22)
    at ExportDefaultVariable.LocalVariable.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:2675:27)
    at Identifier$$1.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:10185:27)
    at LocalVariable.deoptimizePath (/home/rod/work/alchemy/alchemy-gui/node_modules/rollup/dist/rollup.js:2675:27)
```
I'm guessing your built package doesn't export nicely for rollup?

**Comment by Denyllon** [comment]
Hello @rodhoward ,

Thank you for your report.
Basically, this wrapper is bundled as the `UMD` module using webpack, and we've never tested it with Rollup, but I'm guessing that library uses ES modules only, am I right?
If yes, you can try to directly refer to source code included in `highcharts-vue/src/index`, like in below example:
```js
import { Chart } from 'highcharts-vue/src/index'

export default {
  components: {
    highcharts: Chart
  },
  data() {
    return {
      chartOptions: {
        series: [{
          data: [1, 2, 3]
        }]
      }
    };
  }
};
```

Live example: https://codesandbox.io/s/xl68vn94mz

Kind regards!

**Comment by rodhoward** [comment]
Legend, thanks heaps works perfectly! (both via webpack and rollup).

**Comment by Denyllon** [comment]
Thank you for sending configuration. After deep diving into the Rollup documentation and preparing some tests, I found that using named exports like
```js
import { Chart } from 'highcharts-vue'
```
requires to define it within `commonjs` plugin, through `namedExports` key, as it is done with `boostrap-vue` package:

```js
namedExports: [
  'node_modules/highcharts-vue/dist/highcharts-vue.min.js': ['Chart']
]
```

So your configuration should looks like below:

```js
// rollup.config.js
import vue from "rollup-plugin-vue";
import buble from "rollup-plugin-buble";
import replace from "rollup-plugin-replace";
import uglify from "rollup-plugin-uglify-es";
import minimist from "minimist";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import scss from 'rollup-plugin-scss';

const argv = minimist(process.argv.slice(2));

const config = {
  input: "src/entry.js",
  output: {
    name: "AlchemyGui",
    exports: "named"
  },
  plugins: [
    resolve({
      module: true,
      browser: true,
      preferBuiltins: false
    }),
    commonjs({
      namedExports: {
        "node_modules/bootstrap-vue/dist/bootstrap-vue.common.min.js": ["bootstrap-vue"],
        "node_modules/highcharts-vue/dist/highcharts-vue.min.js": ['Chart']
      }
    }),
    scss({ output: "./dist/css/alchemy-gui.css" }),
    replace({
      "process.env.NODE_ENV": JSON.stringify("production")
    }),
    vue({
      css: true,
      compileTemplate: true,
      template: {
        isProduction: true
      }
    }),
    buble({ objectAssign: "Object.assign" })
  ]
};

// Only minify browser (iife) version
if (argv.format === "iife") {
  config.plugins.push(uglify());
}
```

I've tested it, and works well. Here you can find the example package: https://github.com/Denyllon/highcharts-vue-rollup-demo

Kind regards!
